name: CD

on:
    workflow_run:
        workflows: ["CI"]
        types: [ completed ]
        branches: [ actions ]

jobs:
    deploy:
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: self-hosted
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4
            - name: Copy Environment variables
              run:  cp .env.example .env
            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Deploying the container
              run: |
                docker compose pull
                docker compose up -d
