name: CI

on:
  push:
    branches: [actions]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Docker Setup
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify Compose
        run: docker compose version

      - name: Stop existing containers
        run: docker compose down

      - name: Build images
        run: docker compose build

      - name: Start application
        run: docker compose up -d
