# Code Quality Checks using SAST
name: Code Quality

on:
  workflow_call:

jobs:
    sast-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '24'
                  cache: 'npm'
                  cache-dependency-path: frontend/package-lock.json
            - name: Install dependencies
              run: npm ci
              working-directory: ./frontend
            - name: Run lint
              run: |
                npm run lint
              working-directory: ./frontend

    sast-backend:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                  go-version-file: backend/go.mod
                  cache-dependency-path: backend/go.sum
            - name: Install dependencies
              run: go mod download
              working-directory: ./backend
            - name: Run go fmt
              run: go fmt ./...
              working-directory: ./backend  
            - name: Run Go Vet
              run: go vet ./...
              working-directory: ./backend
            - name: Running golangci-lint
              uses: golangci/golangci-lint-action@v9
              with:
                working-directory: backend