# Dependency Scan to ensure that the project dependencies are up to date and free from known vulnerabilities.
name: Dependency Scan

on:
    workflow_call:

jobs:
    dependency-scan-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '20'
                  cache: 'npm'
                  cache-dependency-path: frontend/package-lock.json
            - name: Install dependencies
              run: npm ci
              working-directory: ./frontend
            - name: Run Dependency Scan
              run: |
                mkdir -p reports
                (cd frontend && npm audit) | tee reports/frontend-npm-audit.txt
              working-directory: ./frontend
            - name: Upload Reports
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: dependency-scan-report
                path: reports/
                retention-days: 5
              
            
    dependency-scan-backend:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                  go-version-file: ./backend/go.mod
                  cache-dependency-path: ./backend/go.sum
            - name: Install dependencies
              run: go mod download
              working-directory: ./backend
            - name: Run Dependency Scan
              uses: golang/govulncheck-action@v1
              with:
                work-dir: './backend'

    dependency-scan:
      runs-on: ubuntu-latest
      steps:
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.14'

        - name: pip-audit
          continue-on-error: true
          run: |
            pip install pip-audit
            pip-audit -r ai-service/requirements.txt | tee reports/ai-pip-audit.txt

        - name: Upload Reports
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: dependency-scan-report
            path: reports/
            retention-days: 5