# Dependency Scan to ensure that the project dependencies are up to date and free from known vulnerabilities.
name: Dependency Scan

on:
    workflow_call:

jobs:
    dependency-scan-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '20'
                  cache: 'npm'
                  cache-dependency-path: frontend/package-lock.json
            - name: Install dependencies
              run: npm ci
              working-directory: ./frontend
            - name: Run Dependency Scan
              run: |
                mkdir -p reports
                npm audit --audit-level=high | tee reports/frontend-vuln-report.txt
              working-directory: ./frontend
            - name: Upload Job Report
              uses: actions/upload-artifact@v4
              if: always()  # Forces execution even if tests fail
              with:
                name: frontend-vuln-report # Name of the zip package inside GitHub UI
                path: frontend/reports/frontend-vuln-report.txt     # Absolute or relative path to your file
                retention-days: 7          # Optional expiration timeframe
    dependency-scan-backend:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                  go-version-file: ./backend/go.mod
                  cache-dependency-path: ./backend/go.sum
                  cache: true
            - name: Install dependencies
              run: go mod download
              working-directory: ./backend
            - name: Run Dependency Scan
              run: |
                go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
                mkdir -p reports
                govulncheck ./... > reports/backend-vuln-report.txt
              working-directory: ./backend
              continue-on-error: true # Continue even if the command fails
            - name: Upload Job Report
              uses: actions/upload-artifact@v4
              if: always()  # Forces execution even if tests fail
              with:
                name: backend-vuln-report 
                path: backend/reports/backend-vuln-report.txt     
                retention-days: 7         