# The DevSecOps workflows calling multiple security scans for the project.
# This workflow will run on every push and pull request to the main branch,
# and will scan the code for vulnerabilities using SonarQube, Dependency Scanning, Secret Scanning, and Docker Scanning.
name: Secure Workflow

on:
    push:
        branches:
            - master

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

    docker-scan:
        uses: ./.github/workflows/docker-scan.yml
        secrets: inherit
    
    sonar-scan:
        uses: ./.github/workflows/sonar-scan.yml
        secrets: inherit
    
    code-test:
        uses: ./.github/workflows/code-test.yml

    build-and-push:
        needs: [code-quality,dependency-scan,secret-scanning,docker-scan,sonar-scan,code-test]
        uses: ./.github/workflows/build-push.yml
        secrets: inherit

    deploy:
        needs: [build-and-push]
        uses: ./.github/workflows/cd.yml
        secrets: inherit
    OWASP:
        needs: [deploy]
        uses: ./.github/workflows/dast.yml
        secrets: inherit

    
    