# The DevSecOps workflows calling multiple security scans for the project.
# This workflow will run on every push and pull request to the main branch,
# and will scan the code for vulnerabilities using SonarQube, Dependency Scanning, Secret Scanning, and Docker Scanning.
name: DevSecOps CI

on:
    push:
        branches:
            - actions

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

    docker-scan:
        uses: ./.github/workflows/docker-scan.yml
        secrets: inherit

    