# Ensure Docker images are scanned for vulnerabilities 
name: Docker Scan

on:
    workflow_call:

jobs:
    docker-scan:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dockerfile: [frontend,backend]
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: Docker lint
              uses: hadolint/hadolint-action@v3.1.0
              with:
                  dockerfile: ./${{ matrix.dockerfile }}/Dockerfile
            - name: Docker Login
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build Docker ${{ matrix.dockerfile }} Image
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.dockerfile }} ./${{ matrix.dockerfile }}
              working-directory: ./${{ matrix.dockerfile }}
            - name: Scan Docker ${{ matrix.dockerfile }} Image
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                    image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.dockerfile }}
                    format: 'table'
                    exit-code: '1'
                    ignore-unfixed: true
                    vuln-type: 'os,library'
                    severity: 'CRITICAL,HIGH'