# Secret Scanning for secret leaks in the codebase. This workflow will run on every push and pull request to the main branch, and will scan the code for secrets using GitHub's Secret Scanning feature.
name: Secret Scanning

on:
    workflow_call:

jobs:
    secret-scanning:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0
            - name: GitLeaks
              uses: gitleaks/gitleaks-action@v8
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              